allowBuilds:
  '@prisma/engines': true
  esbuild: set this to true or false
  msw: true
  prisma: false
  sharp: true
  unrs-resolver: false
  yarn: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - shadcn@4.10.0
